### ISSUE TITLE
public/locallogin.html bugs (Team3_issue)

### ISSUE THREAD

**Issue by MahmoudMagdyKamal** [ELG7186-s22/project-group-3#1]
1)Add "lang" and/or "xml:lang" attributes to this "<html>" element.
#line 2 in locallogin.html file
#desc:- 
The <html> element should provide the lang and/or xml:lang attribute in order to identify the default language of a document.

It enables assistive technologies, such as screen readers, to provide a comfortable reading experience by adapting the pronunciation and accent to the language. It also helps braille translation software, telling it to switch the control codes for accented characters for instance.

Other benefits of marking the language include:

    -assisting user agents in providing dictionary definitions or helping users benefit from translation tools.
    -improving search engine ranking.

Both the lang and the xml:lang attributes can take only one value.
2)Add an "alt" attribute to this image.
#line 156 & 270 in locallogin.html file
#desc:-
It is also very important to not set an alt attribute to a non-informative value. For example <img ... alt="logo"> is useless as it doesn’t give any information to the user. In this case, as for any other decorative image, it is better to use a CSS background image instead of an <img> tag. If using CSS background-image is not possible, an empty alt="" is tolerated. See Exceptions bellow.

This rule raises an issue when

    -an <input type="image"> tag or an <area> tag have no alt attribute or their alt attribute has an empty string value.
    -an <img> tag has no alt attribute.

**Comment by norantharowat** [comment]
Fixed.

**Comment by MahmoudMagdyKamal** [comment]
great job Noran, Thank you.
