### ISSUE TITLE
Missing feature (Team2)

### ISSUE THREAD

**Issue by AhmedYHamza** [ELG7186-s22/project-group-3#10]
When accessing your code we didn’t find one of the most important requirements: which is that the instructor should have the ability to limit students’ progress up to a specific level/belt.

**Comment by norantharowat** [comment]
I think you have a misunderstanding, actually we should leave the belts available for students to play, we only should hide the view solution button for the selected belts, which we did.

Here is a slack conversation with the TA confirming this point. 
![image](https://user-images.githubusercontent.com/43759597/182222985-1fcea021-4bca-4eab-9795-b65a95cfa5d7.png)

**Comment by AhmedYHamza** [comment]
Actually, this is a core functionality that is introduced explicitly in the project description before the point you asked Sumit about. Please find an attachment with the functionality described in the highlighted lines. 
![Screenshot 2022-08-01 210856](https://user-images.githubusercontent.com/66231209/182227605-e9e3e04e-38d5-4104-bb00-461e8b776f52.jpg)

**Comment by AhmedYHamza** [comment]
Turns out that this isn't really an issue. We didn't know that this feature wasn't a requirement due to the vague nature of the project overview. Sorry for troubling you.
