### ISSUE TITLE
unauthorized redirect (Team 2)

### ISSUE THREAD

**Issue by AhmedYHamza** [ELG7186-s22/project-group-3#11]
A regular user is able to access any page within the static directory, including but not limited to the instructor page"/main/myStudents", though you cannot change any thing. But that discloses the structure of the page to unauthorized users.
![3](https://user-images.githubusercontent.com/66231209/182234165-d3dd7476-7c98-4118-9cf3-86eec5cd2540.jpg)
![2](https://user-images.githubusercontent.com/66231209/182234176-5cb6c17d-9db5-403c-a4df-68e5b2c6248b.jpg)
![1](https://user-images.githubusercontent.com/66231209/182234182-62b4e20c-ee37-4fdb-bb6c-be4184b6e235.jpg)

**Comment by OmniaSolimanMohamed** [comment]
fixed, thank you. 
![image](https://user-images.githubusercontent.com/47222715/183541027-a5865075-44ad-4ad8-b855-cb8d83e00642.png)
![image](https://user-images.githubusercontent.com/47222715/183541100-c3511996-8e05-48fc-8e41-31e39c414e2a.png)
