### ISSUE TITLE
CWE-552: Files or Directories Accessible to External Parties(team4) (Critical)

### ISSUE THREAD

**Issue by atia98** [ELG7186-s22/project-group-3#15]
![WhatsApp Image 2022-08-05 at 1 50 50 AM](https://user-images.githubusercontent.com/57109699/182974164-1ddcf532-45e6-459c-9cd8-ad13bcc2d9be.jpeg)
![WhatsApp Image 2022-08-05 at 1 51 13 AM](https://user-images.githubusercontent.com/57109699/182974167-40a0f79a-f7d3-4d45-81bf-1917519486ed.jpeg)

a student can access challenges solution even though he or she is prevented
example: 
I can know all information about challenges from unauthorized  browsing for [](https://secure-coding-dojo-group-3.herokuapp.com/static/lessons/blackBelt/definitions.json) 
by knowing the challenge id i can unauthorized  access the challenge html page [](https://secure-coding-dojo-group-3.herokuapp.com/static/lessons/blackBelt/cwe807.html) and download the file.sol.md [](https://secure-coding-dojo-group-3.herokuapp.com/static/lessons/blackBelt/cwe807.sol.md)

**Comment by norantharowat** [comment]
Thank you for pointing this issue.
