### ISSUE TITLE
CWE-807: Reliance on Untrusted Inputs in a Security Decision (Critical!) (Team 4)

### ISSUE THREAD

**Issue by MagicianMido32** [ELG7186-s22/project-group-3#17]
a malicious instructor user can control other students belonging to other instructors (assuming that you somehow fixed issue  #13  or limited student to not be able to un-join instructor - which is only done in the client side app and easily bypassed)) 
just tampering with the parameter student_id gives you unlimited access to all students in the website 
![image](https://user-images.githubusercontent.com/17013016/182979630-3f79a891-cd98-47c9-b295-810ce75afb79.png)
You don't check if this student belong to this instructor or not 
![image](https://user-images.githubusercontent.com/17013016/182979852-4f49cbae-1fe3-4a63-813e-b01ccd8c00c1.png)

**Comment by norantharowat** [comment]
Yes, we are aware of this issue, since we had limited time, we were not able to handle each possible case. Thank you for pointing this issue.
