### ISSUE TITLE
CWE-434: Unrestricted Upload of File with Dangerous Type(team 4) 

### ISSUE THREAD

**Issue by atia98** [ELG7186-s22/project-group-3#18]
![WhatsApp Image 2022-08-05 at 3 16 04 AM](https://user-images.githubusercontent.com/57109699/182981137-9346c877-55ad-462c-b641-06e5c39f0628.jpeg)
a malicious actor can upload malicious file instead of csv file

**Comment by norantharowat** [comment]
This issue does not belong to our own written code, thank you for pointing this issue, but it will be out of scope during fixing.

**Comment by OmniaSolimanMohamed** [comment]
Done, thank you.
