### ISSUE TITLE
static/myStudents.html (Team3_issue)

### ISSUE THREAD

**Issue by MahmoudMagdyKamal** [ELG7186-s22/project-group-3#2]
1)Add a description to this table.
#line 9 
#desc:-
In order to be accessible to visually impaired users, it is important that tables provides a description of its content before the data is accessed.

The simplest way to do it, and also the one recommended by WCAG2 is to add a <caption> element inside the <table>.

Other technics this rule accepts are:

    -adding a concise description via aria-label or aria-labelledby attributes in the <table>.
    -referencing a description element with an aria-describedby attribute in the <table>.
    -embedding the <table> inside a <figure> which also contains a <figcaption>.
    -adding a summary attribute to the <table> tag. However note that this attribute has been deprecated in HTML5.

See W3C WAI Web Accessibility Tutorials for more information.

This rule raises an issue when a <table> has neither of the previously mentioned description mechanisms.

**Comment by norantharowat** [comment]
Added the table caption, and fixed it.

**Comment by MahmoudMagdyKamal** [comment]
great job Noran, Thank you.
