### ISSUE TITLE
aescrypto.js (Team 3_issue)

### ISSUE THREAD

**Issue by MahmoudMagdyKamal** [ELG7186-s22/project-group-3#3]
1)Use a secure mode and padding scheme.
#line 29
#desc:-
Encryption operation mode and the padding scheme should be chosen appropriately to guarantee data confidentiality, integrity and authenticity:

    -For block cipher encryption algorithms (like AES):
        -The GCM (Galois Counter Mode) mode which works internally with zero/no padding scheme, is recommended, as it is designed to provide both data authenticity (integrity) and confidentiality. Other similar modes are CCM, CWC, EAX, IAPM and OCB.
        -The CBC (Cipher Block Chaining) mode by itself provides only data confidentiality, it’s recommended to use it along with Message Authentication Code or similar to achieve data authenticity (integrity) too and thus to prevent padding oracle attacks.
       - The ECB (Electronic Codebook) mode doesn’t provide serious message confidentiality: under a given key any given plaintext block always gets encrypted to the same ciphertext block. This mode should not be used.
    -For RSA encryption algorithm, the recommended padding scheme is OAEP.

#solution:-
crypto.createCipheriv("AES-256-GCM", key, iv);

**Comment by norantharowat** [comment]
Fixed.

**Comment by MahmoudMagdyKamal** [comment]
great job Noran, Thank you.
